import express from "express";
import { login, recoverAccount, registerSchool, verifyEmail } from "../controllers/userController.js";
import uploads from "../middleware/uploads.js";
const userRouter = express.Router();
userRouter.post("/register", uploads.single("image"), registerSchool);
userRouter.post("/login", login);
userRouter.post("/verifyemail/:token", verifyEmail);
userRouter.post("/recoveraccount", recoverAccount);
userRouter.post("/resetpassword/:token", resetpassword);
export { userRouter };
